version: "0.0"
name: frontend
services:
  frontend:
    environment:
      - REACT_APP_BASE_URL=http://127.0.0.1:8080
    image: web-shop/dev
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: web-shop-dev
    volumes:
      - ./src:/app/src
      - ./node_modules:/app/node_modules
      - ./public:/app/public
    ports:
      - 3500:3000
