version: "3"
name: shop-server-dev
services:
  shop-server-dev:
    image: shop-server/dev
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: shop-server-dev
    volumes:
      - ./src:/app/src
    ports:
      - 8080:3000
